[project]
name = "fuzzy-hash"
version = "0.1.0"
description = "Plateforme de test fuzzy hashing"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "ipython>=8.31.0",
    "maturin>=1.8.1",
    "pandas>=2.2.3",
    "pyright>=1.1.392",
    "sqlalchemy>=2.0.37",
]
