[project]
name = "fuzzy-hash"
version = "0.1.0"
description = "Plateforme de test fuzzy hashing"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "ipython>=8.31.0",
    "ipympl>=0.9.6",
    "maturin>=1.8.1",
    "jupyterthemes>=0.20.0",
    "pandas>=2.2.3",
    "progress>=1.6",
    "pyright>=1.1.392",
    "sqlalchemy>=2.0.37",
    "dash>=3.0.2",
    "dash-mantine-components>=1.1.1",
    "pygwalker>=0.4.9.13",
    "ipykernel>=6.29.5",
    "fuzzylib",
    "dangerously-set-inner-html",
]

[tool.uv.sources]
fuzzylib = { path = "fuzzylib/bindings" }
dangerously-set-inner-html = { path = "dashboard/dangerously_set_inner_html/dist/dangerously_set_inner_html-0.0.1-py3-none-any.whl" }

