# Generated by Django 5.1.1 on 2024-09-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('sid', models.CharField(max_length=512, unique=True)),
                ('path', models.CharField(max_length=4096, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=512, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('path', models.CharField(max_length=4096, unique=True)),
                ('signature', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.algo')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sample')),
            ],
            options={
                'unique_together': {('algo', 'sample')},
            },
        ),
    ]
