pub const LONG_STRING_1 : &[u8] = b"
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello world this is me mario! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
";


pub const LONG_STRING_2 : &[u8] = b"
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
hello warld this is me maria! jalekjfamlekjfam emlkaefjmlkeajf almjfmlakjfeamlkfejamlfkajfmlekajfmlkejfnvwx;nc;wnfiepoizejfmlkfqjmldsjfdsaeflkaejlfak
";
